# Generated by Django 5.1.3 on 2024-11-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav_manufacturing_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_montage_team',
        ),
        migrations.AddField(
            model_name='team',
            name='is_assembly_tea',
            field=models.BooleanField(default=False),
        ),
    ]
