# Generated by Django 5.1.3 on 2024-11-14 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav_manufacturing_application', '0002_employee_user_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='part_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uav_manufacturing_application.parttype'),
        ),
    ]
