# Generated by Django 5.1.3 on 2024-11-17 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uav_manufacturing_application', '0002_remove_team_is_montage_team_team_is_assembly_tea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='is_assembly_tea',
            new_name='is_assembly_team',
        ),
    ]
