# Generated by Django 5.1.3 on 2024-11-16 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav_manufacturing_application', '0002_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
        ),
    ]
