# Generated by Django 5.1.3 on 2024-11-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uav_manufacturing_application', '0003_uav_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uav',
            name='name',
        ),
    ]
