# Generated by Django 5.1.3 on 2024-11-16 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav_manufacturing_application', '0004_remove_uav_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uav',
            name='model',
        ),
        migrations.AddField(
            model_name='uav',
            name='uav_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='uav_types', to='uav_manufacturing_application.uavtype'),
        ),
    ]
