# Generated by Django 5.1.3 on 2024-11-16 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav_manufacturing_application', '0005_remove_uav_model_uav_uav_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='name',
        ),
        migrations.RemoveField(
            model_name='part',
            name='uav',
        ),
        migrations.AddField(
            model_name='part',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
