# Generated by Django 5.1.3 on 2024-11-16 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav_manufacturing_application', '0006_remove_part_name_remove_part_uav_part_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='uav',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='uav_manufacturing_application.uav'),
        ),
    ]
