# Generated by Django 5.1.3 on 2024-11-16 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav_manufacturing_application', '0007_part_uav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='uav',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='uav_manufacturing_application.uav'),
        ),
    ]
